Openspp 17.0.1.2
OpenSPP/openspp-docker pull request #24
Opened 2024-09-05 05:22 UTC by kneckinator

Adding OpenSPP's pip-requirements to allow for installing all OpenSPP modules, switching to supported Odoo version (odoo/odoo), removing commented out repos, switching to use OpenSPP's forks of dependency libraries

2024-09-05 06:21 UTC, kneckinator commented
Moved to "draft" as a final self-review found one issue and one additional feature this change could solve, which is the ability to set the OpenSPP version to use via a docker argument. This will make it easier to use a specific branch of OpenSPP instead of being stuck with 17.0

2024-09-11 08:13 UTC, dasunhegoda requested changes
```
Invalid Operation

Unable to install module "spp_base" because an external dependency is not met: Python library not installed: fastapi==0.112.2
```

I get the above error when I try to install `openspp_base`.

2024-09-12 02:58 UTC, kneckinator commented
> ```
> Unable to install module "spp_base" because an external dependency is not met: Python library not installed: fastapi==0.112.2
> ```
> 
> I get the above error when I try to install `openspp_base`. Also the `Quality Gate failed`

Regarding fastapi, that was weird @dasunhegoda, as the library is pinned.
Can you:
- connect to the container and check the Python dependencies (`pip freeze`) and check if you have dependencies matching https://github.com/OpenSPP/openspp-docker/blob/openspp-17.0.1.2/odoo/custom/dependencies/pip.txt ?
-  clone the repo to a fresh folder and see if you get the same results?

> Also the `Quality Gate failed`
This is ok, as this is a development image and root is required by https://github.com/Tecnativa/doodba/blob/master/17.0.Dockerfile

2024-09-12 03:01 UTC, kneckinator commented
Quality gate failure has been reviewed and handled.

2024-09-12 09:29 UTC, dasunhegoda commented
@kneckinator For some reason, I don't have the `fastapi` in the docker when I do `pip freeze` and I started fresh.

2024-09-12 09:31 UTC, dasunhegoda commented
@kneckinator For some reason, I don't have the `fastapi` in the docker when I do `pip freeze` and I started fresh (branch:`openspp-17.0.1.2`)

2024-09-12 09:59 UTC, dasunhegoda commented
@kneckinator : I get this error now

`while parsing /opt/odoo/auto/addons/stock/data/stock_demo.xml:133, somewhere inside <record id="res_partner_company_1" model="res.partner"> <field name="name">My Company, Chicago</field> <field name="is_company">1</field> <field eval="1" name="active"/> <field name="street">90 Streets Avenue</field> <field model="res.country" name="country_id" search="[('code','ilike','us')]"/> <field model="res.country.state" name="state_id" search="[('code','ilike','il')]"/> <field name="zip">60610</field> <field name="city">Chicago</field> <field name="email">chicago@yourcompany.com</field> <field name="phone">+1 312 349 3030</field> <field name="website">www.example.com</field> <field name="company_id" eval="False"/> </record>`

2024-09-13 04:28 UTC, kneckinator commented
> @kneckinator : I get this error now
> 
> `while parsing /opt/odoo/auto/addons/stock/data/stock_demo.xml:133, somewhere inside <record id="res_partner_company_1" model="res.partner"> <field name="name">My Company, Chicago</field> <field name="is_company">1</field> <field eval="1" name="active"/> <field name="street">90 Streets Avenue</field> <field model="res.country" name="country_id" search="[('code','ilike','us')]"/> <field model="res.country.state" name="state_id" search="[('code','ilike','il')]"/> <field name="zip">60610</field> <field name="city">Chicago</field> <field name="email">chicago@yourcompany.com</field> <field name="phone">+1 312 349 3030</field> <field name="website">www.example.com</field> <field name="company_id" eval="False"/> </record>`

This is "fine" @dasunhegoda . That demo data is not compatible with OpenSPP. But we should fix it later.

2024-09-13 05:05 UTC, dasunhegoda commented
@kneckinator : Noted. I will approve now.

2024-09-13 05:05 UTC, dasunhegoda approved these changes

2024-09-19 02:09 UTC, merged