added option to initialize database without demo data
OpenSPP/openspp-docker pull request #8
Opened 2023-06-27 02:05 UTC by reichie020212

- Added new parameter in resetdb named nodemo and default is False
- use "invoke resetdb --nodemo" to initialize a db without demo data
- use "invoke resetdb" to initialize a db with demo data
- updated README.md

2023-06-30 02:46 UTC, nhatnm0612 approved these changes

2023-06-30 03:03 UTC, gonzalesedwin1123 requested changes

2023-06-30 03:03 UTC, gonzalesedwin1123 commented on tasks.py
@reichie020212 can we set the **nodemo** to be the default?

2023-06-30 03:31 UTC, reichie020212 commented on tasks.py
sure @gonzalesedwin1123

2023-06-30 04:03 UTC, reichie020212 commented on tasks.py
@gonzalesedwin1123 done changing the nodemo to default

2023-06-30 06:21 UTC, gonzalesedwin1123 approved these changes

2023-10-09 03:15 UTC, jeremi approved these changes

2023-10-09 03:16 UTC, merged